[project]
name = "design-pattern-practice"
version = "0.1.0"
description = "Practicing design patterns in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "rich>=14.2.0",
]
